// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3777.FakeRobot.commands;

import edu.wpi.first.wpilibj.command.PIDCommand;
import org.usfirst.frc3777.FakeRobot.Robot;
import org.usfirst.frc3777.FakeRobot.RobotMap;

/**
 *
 */
public class PIDCommand2 extends PIDCommand {


    public PIDCommand2() {

  
        super("PIDCommand2", 3.0, 0.0, 0.0, 0.02);
        getPIDController().setContinuous(false);
        getPIDController().setAbsoluteTolerance(0.2);

   
    }

    protected double returnPIDInput() {

        return RobotMap.elevatorPotentiometer.pidGet();

   
    }

    protected void usePIDOutput(double output) {
        
        RobotMap.elevatorCANTalon1.pidWrite(output);

    }

    protected void initialize() {
    }

    protected void execute() {
    }

    protected boolean isFinished() {
        return false;
    }

    protected void end() {
    }

    protected void interrupted() {
    }
}
