// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3777.FakeRobot.subsystems;

import org.usfirst.frc3777.FakeRobot.RobotMap;
import org.usfirst.frc3777.FakeRobot.commands.*;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drive extends Subsystem {

    
    private final CANTalon talon1 = RobotMap.driveTalon1;
    private final CANTalon talon2 = RobotMap.driveTalon2;
    private final CANTalon talon3 = RobotMap.driveTalon3;
    private final CANTalon talon4 = RobotMap.driveTalon4;
    public final RobotDrive robotDrive = RobotMap.driveRobotDrive;

 

    public void initDefaultCommand() {
      

        setDefaultCommand(new DrivewithJoy());

   
    }
    public void takeJoystickInputs(Joystick left, Joystick right) {
    	robotDrive.tankDrive(left, right);
    }
    public void stop(){
    	robotDrive.drive(0, 0);
    }
}


