// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3777.FakeRobot.subsystems;

import org.usfirst.frc3777.FakeRobot.OI;
import org.usfirst.frc3777.FakeRobot.RobotMap;
import org.usfirst.frc3777.FakeRobot.commands.*;
import org.usfirst.frc3777.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Solenoid;


/**
 * 
 */
public class Pneumatics extends Subsystem {

   
public static DoubleSolenoid doubleSolenoid1 = RobotMap.pneumaticsDoubleSolenoid1;

   

    public void initDefaultCommand() {

    	}
}


